[left]
enter_command = [ "hyprctl", "dispatch workspace -1" ]
exit_command = [ ]
locations = [ "bottom_left" ]
size = 10
margin = 20
timeout_ms = 250
color = "#FFFF0000"

[top_left]
enter_command = [ "wlogout" ]
exit_command = [ ]
locations = [ "top_left" ]
size = 10
margin = 20
timeout_ms = 250
color = "#FFFF0000"

[right]
enter_command = [ "hyprctl", "dispatch workspace +1" ]
exit_command = [ ]
locations = [ "bottom_right" ]
size = 10
margin = 20
timeout_ms = 250
color = "#FFFF0000"

[top_right]
enter_command = [ "hyprlock" ]
exit_command = [ ]
locations = [ "top_right" ]
size = 10
margin = 20
timeout_ms = 250
color = "#FFFF0000"
